conf = {'clients': [{'name': 'non-sequencer',
                     'type': 'midi',
                     'tracks': {'bass_drum': {'label': 'bass_drum',
                                              'type': 'control_change',
                                              'note': 0,
                                              'data': {'channel': 0,
                                                             'control': 20,
                                                             'velocity': 64,
                                                             'value': 0,
                                                             'pitch': 0,
                                                             'data': 0,
                                                             'frame_type': 0,
                                                             'frame_value': 0,
                                                             'pos': 0,
                                                             'song': 0}},
                                'snare_hihat': {'label': 'snare_hihat',
                                                'type': 'control_change',
                                                'data': {'channel': 0,
                                                               'note': 0,
                                                               'control': 21,
                                                               'velocity': 64,
                                                               'value': 0,
                                                               'pitch': 0,
                                                               'data': 0,
                                                               'frame_type': 0,
                                                               'frame_value': 0,
                                                               'pos': 0, 'song': 0}}}}],
        'controllers': [{'name': 'fc300',
                         'type': 'midi',
                         'signal_map': {'B0 41 00': '1a',
                                        'B0 41 7F': '1b',
                                        'B0 50 00': 'modeswitch',
                                        'B0 50 7F': 'modeswitch1',
                                        'B0 42 00': '2a',
                                        'B0 42 7F': '2b'}}],
        'scenes': {'scene1': {'non-sequencer': ['bass_drum', 'snare_hihat']},
                   'scene2': {'': ['']}},
        'controller_signal_scene_map': {'fc300': {'1a': 'scene1', '1b': 'scene1', '2b': 'scene2', '2a': 'scene2'}},
        'controller_signal_trigger_map': {'fc300': {'1a': {'non-sequencer': ['bass_drum']},
                                                    '1b': {'non-sequencer': ['bass_drum']},
                                                    '2b': {'non-sequencer': ['snare_hihat']},
                                                    '2': {'non-sequencer': ['snare_hihat']},
                                                    '2a': {'non-sequencer': ['snare_hihat']}}},
        'mode_switch': {'fc300': ['modeswitch', 'modeswitch1']}}
